routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::middleware('auth')->group(function (){
    Route::softDeletes('users', \App\Http\Controllers\web\UserController::class);
    Route::resource('/users', \App\Http\Controllers\web\UserController::class);

});

app/Models/Detail.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Detail extends Model
{
    use HasFactory;
    protected $guarded=['id'];
    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use App\Enums\UserEnum;
use App\Events\UserSaved;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Str;
use Laravel\Sanctum\HasApiTokens;
use Illuminate\Database\Eloquent\Casts\Attribute;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable,SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $guarded = ['id'];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    protected $dispatchesEvents=[
        'saved' => UserSaved::class,
    ];
    /**
     * Get the user's first name.
     *
     * @param  string  $value
     * @return string
     */
    public function getPhotoAttribute($value)
    {
        return $value != null ? asset('storage/' . $value) : asset('default_images/user.jpg');
    }

    public function getFullnameAttribute()
    {
        return Str::replace('  ',' ',$this->firstname .' '.$this->middleinitial.' '.$this->lastname);
    }
    public function getMiddleinitialAttribute ()
    {
        $firstChar = Str::substr($this->middlename, 0, 1);
        return $firstChar ? Str::upper($firstChar) . '.' : '';
    }
    public function details()
    {
        return $this->hasMany(Detail::class);
    }
    public function getGenderAttribute()
    {
        return Str::lower($this->prefixname)==Str::lower(UserEnum::MR)?'Male':'Female';
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class UsersController extends Controller
{
    //
}

app/Http/Controllers/web/UserController.php
<?php

namespace App\Http\Controllers\web;

use App\DataTables\UserDataTable;
use App\Http\Controllers\Controller;
use App\Http\Requests\user\UserRequest;
use App\Models\User;
use App\Services\UserService;

class UserController extends Controller
{
    private $UserService;
    public function __construct(UserService $UserService)
    {
        $this->UserService=$UserService;
    }

    public function index(UserDataTable $dataTable )
    {
        return $dataTable->render('users.index');
    }
    public function create()
    {
        return view('users.create');
    }
    public function store(UserRequest $request)
    {
        $this->UserService->store($request->validated());
        return redirect(route('users.index'));
    }
    public function edit(User $user)
    {
        return view('users.edit',compact('user'));
    }
    public function show(User $user)
    {
        return view('users.show',compact('user'));
    }
    public function update($id, UserRequest $request)
    {
        $this->UserService->update($id,$request->validated());
        return redirect(route('users.index'));
    }
    public function destroy($id)
    {
        $this->UserService->destroy($id);
        return redirect(route('users.index'));
    }
    public function trashed(UserDataTable $dataTable)
    {
        return $dataTable->render('users.index');
    }
    public function restore($id)
    {
        $this->UserService->restore($id);
        return redirect(route('users.index'));
    }

    public function delete($id)
    {
        $this->UserService->delete($id);
        return redirect(route('users.index'));
    }
}

app/View/Components/layouts/navbar.php
<?php

namespace App\View\Components\layouts;

use Illuminate\View\Component;

class navbar extends Component
{
    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|\Closure|string
     */
    public function render()
    {
        return view('components.layouts.navbar');
    }
}

resources/views/home.blade.php
@extends('layouts.dashboard.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.bunny.net/css?family=Nunito" rel="stylesheet">

    <!-- Scripts -->
    @vite(['resources/sass/app.scss', 'resources/js/app.js'])
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav me-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ms-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
    @stack('scripts')
</body>
</html>

resources/views/layouts/dashboard/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.bunny.net/css?family=Nunito" rel="stylesheet">

    <!-- Scripts -->
    @vite(['resources/sass/app.scss', 'resources/js/app.js'])
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav me-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ms-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{auth()->user()->username}}
                                </a>

                                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="container-fluid">
            <div class="row flex-nowrap">
                <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-dark">
                    <x-layouts.navbar/>
                </div>
                <div class="col py-3">
                    @yield('content')
                </div>
            </div>
        </main>
    </div>
    @stack('scripts')
</body>
</html>

resources/views/users/create.blade.php
@extends('layouts.dashboard.app')
@section('content')
    <div class="container p-4">
        <form  method="POST" action="{{route('users.store')}}" enctype="multipart/form-data">
            @csrf()
            <div class="row">
                <div class="form-group ">
                    <label class="required-label">prefix name</label>
                    <select name="prefixname" class="form-control">
                        @foreach(\App\Enums\UserEnum::getPrefixName() as $prefix)
                            <option value="{{$prefix}}">{{$prefix}}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group ">
                    <label class="required-label">first name</label>
                    <input type="text" name="firstname" class="form-control" value="{{old('firstname')}}">
                </div>
                <div class="form-group ">
                    <label class="required-label">middlename</label>
                    <input type="text" name="middlename" class="form-control" value="{{old('middlename')}}">
                </div>
                <div class="form-group ">
                    <label class="required-label">last name</label>
                    <input type="text" name="lastname" class="form-control" value="{{old('lastname')}}">
                </div>
                <div class="form-group ">
                    <label class="required-label">suffix name</label>
                    <input type="text" name="suffixname" class="form-control" value="{{old('suffixname')}}">
                </div>
                <div class="form-group ">
                    <label class="required-label">username</label>
                    <input type="text" name="username" class="form-control" value="{{old('username')}}">
                </div>
                <div class="form-group ">
                    <label class="required-label">email</label>
                    <input type="email" name="email" class="form-control" value="{{old('email')}}">
                </div>
                <div class="form-group ">
                    <label class="required-label">password</label>
                    <input type="password" name="password" class="form-control">
                </div>
                <div class="form-group ">
                    <label class="required-label">password confirmation </label>
                    <input type="password" name="password_confirmation" class="form-control">
                </div>
                <div class="form-group ">
                    <label class="required-label">type</label>
                    <input type="text" name="type" class="form-control" value="{{old('type')}}">
                </div>
                <div class="form-group ">
                    <label for="date-format">photo</label>
                    <div>
                        <input type="file" name="photo" class="form-control floating-label date-format" placeholder="Begin Date Time">
                    </div>
                </div>
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <div class="form-group">
                    <button type="submit" class=" btn btn-xs btn-primary px-5 mr-2 form-control">
                        Add
                    </button>
                </div>

            </div>
        </form>
    </div>
@stop

resources/views/users/edit.blade.php
@extends('layouts.dashboard.app')
@section('content')
    <div class="container p-4">
        <form  method="POST" action="{{route('users.update',$user->id)}}" enctype="multipart/form-data">
            @csrf()
            @method('PUT')
            <div class="row">
                <div class="form-group ">
                    <label class="required-label">prefix name</label>
                    <select name="prefixname" class="form-control">
                        @foreach(\App\Enums\UserEnum::getPrefixName() as $prefix)
                            <option value="{{$prefix}}" @if($user->prefixname=="$prefix")selected @endif()>{{$prefix}}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group ">
                    <label class="required-label">first name</label>
                    <input type="text" name="firstname" class="form-control" value="{{$user->firstname}}">
                </div>
                <div class="form-group ">
                    <label class="required-label">middlename</label>
                    <input type="text" name="middlename" class="form-control" value="{{$user->middlename}}">
                </div>
                <div class="form-group ">
                    <label class="required-label">last name</label>
                    <input type="text" name="lastname" class="form-control" value="{{$user->lastname}}">
                </div>
                <div class="form-group ">
                    <label class="required-label">suffix name</label>
                    <input type="text" name="suffixname" class="form-control" value="{{$user->suffixname}}">
                </div>
                <div class="form-group ">
                    <label class="required-label">username</label>
                    <input type="text" name="username" class="form-control" value="{{$user->username}}">
                </div>
                <div class="form-group ">
                    <label class="required-label">email</label>
                    <input type="email" name="email" class="form-control" value="{{$user->email}}">
                </div>
                <div class="form-group ">
                    <label class="required-label">password</label>
                    <input type="password" name="password" class="form-control">
                </div>
                <div class="form-group ">
                    <label class="required-label">password confirmation </label>
                    <input type="password" name="password_confirmation" class="form-control">
                </div>
                <div class="form-group ">
                    <label class="required-label">type</label>
                    <input type="text" name="type" class="form-control" value="{{$user->type}}">
                </div>
                <div class="form-group ">
                    <label for="date-format">photo</label>
                    <div>
                        <input type="file" name="photo" class="form-control floating-label date-format" placeholder="Begin Date Time">
                    </div>
                </div>
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <div class="form-group">
                    <button type="submit" class=" btn btn-xs btn-primary px-5 mr-2 form-control">
                        update
                    </button>
                </div>

            </div>
        </form>
    </div>
@stop

resources/views/users/index.blade.php
@extends('layouts.dashboard.app')

@section('content')
    <div class="container">
        <div class="card">
            <div class="card-header">Manage Companies</div>
            <div class="card-body">
                <button class="btn btn-success"><a style="color: white;text-decoration: none" href="{{route('users.create')}}">Add User</a></button>
                @if(Str::contains(request()->fullUrl() , route('users.trashed')))
                    <button class="btn btn-success"><a style="color: white;text-decoration: none" href="{{route('users.index')}}">users</a></button>
                @else
                    <button class="btn btn-success"><a style="color: white;text-decoration: none" href="{{route('users.trashed')}}">trashed</a></button>
                @endif

                {{ $dataTable->table() }}
            </div>
        </div>
    </div>
@endsection

@push('scripts')
    {{ $dataTable->scripts(attributes: ['type' => 'module']) }}
@endpush

resources/views/users/show.blade.php
@extends('layouts.dashboard.app')
@section('content')
    <div class="container p-4">
        <form  method="POST" action="{{route('users.update',$user->id)}}" enctype="multipart/form-data">
            @csrf()
            @method('PUT')
            <div class="row">
                <div class="form-group ">
                    <label class="required-label">prefix name : {{$user->prefixname}}</label>
                </div>
                <div class="form-group ">
                    <label class="required-label">first name : {{$user->firstname}}</label>
                </div>
                <div class="form-group ">
                    <label class="required-label">middle name : {{$user->middlename}}</label>
                </div>
                <div class="form-group ">
                    <label class="required-label">last name : {{$user->lastname}}</label>
                </div>
                <div class="form-group ">
                    <label class="required-label">suffix name : {{$user->suffixname}}</label>
                </div>
                <div class="form-group ">
                    <label class="required-label">username : {{$user->username}}</label>
                </div>
                <div class="form-group ">
                    <label class="required-label">email : {{$user->email}}</label>
                </div>
                <div class="form-group ">
                    <label class="required-label">type : {{$user->type}}</label>
                </div>
                <div class="form-group ">
                    <label for="date-format">photo</label>
                    <div>
                        <img src="{{$user->photo}}" alt="{{$user->username}}" width="150" height="150">
                    </div>
                </div>
            </div>
        </form>
    </div>
@stop